# version: '3.1'

# services:
#   postgres:
#     image: postgres
#     restart: always
#     ports: 
#     - 5432:5433
#     environment:
#       POSTGRES_USER: dubciuc
#       POSTGRES_PASSWORD: dubciuc


version: '3'
services:
   backend:
      build:
         dockerfile: Dockerfile.back
      ports:
         - "5400:5400"

   db:
      build:
         dockerfile: Dockerfile.db
      ports:
         - "5433:5432"
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: dubciuc
         POSTGRES_PASSWORD: dubciuc
         